<?php
/**
 * Mentors Data for RCOEM TBI Foundation
 *
 * @package TBI_Theme
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

function tbi_get_mentors_data() {
    return [
        [
            'id'          => 1,
            'name'        => 'Dr. Prabodh Halde',
            'designation' => 'Head Regulatory Affairs',
            'company'     => 'Marico',
            'description' => 'Dr. Prabodh Halde leads Marico’s regulatory affairs division with over 30 years of expertise in food processing technology.',
            'mentorship'  => 'Technology',
            'category'    => 'technology',
            'image'       => '1prabodh-ALpnKx3OoPu67W8k.jpg',
        ],
        [
            'id'          => 2,
            'name'        => 'Vaibhav Girmil',
            'designation' => 'Senior Manager',
            'company'     => 'Punjab National Bank',
            'description' => 'Mr. Vaibhav Girmil is an accomplished Senior Manager at PNB with 12 years of expertise in treasury operations and foreign exchange.',
            'mentorship'  => 'Finance',
            'category'    => 'finance',
            'image'       => '3vaibhav-m5KwB6qLrGSEqVro.jpg',
        ],
        [
            'id'          => 3,
            'name'        => 'Goutam Dutta',
            'designation' => 'Senior Advisory Solution Architect',
            'company'     => 'IBM',
            'description' => 'Mr. Goutam Dutta leverages 24 years of industry experience providing cutting-edge solutions and strategic advisory.',
            'mentorship'  => 'Product Development',
            'category'    => 'product-development',
            'image'       => '2goutam-AR0yovxJZksEoz0b.jpg',
        ],
        [
            'id'          => 4,
            'name'        => 'Deepak Jha',
            'designation' => 'Product Manager',
            'company'     => 'Lightbeam AI',
            'description' => 'A seasoned Product Manager with experience across AI, Security, Privacy, Healthcare, and Social Media industries.',
            'mentorship'  => 'Early Stage Ideation',
            'category'    => 'ideation',
            'image'       => '4deepak-AVLp26EaWksN29jz.jpg',
        ],
        [
            'id'          => 5,
            'name'        => 'Sarika Narayan',
            'designation' => 'Independent Business Consultant',
            'company'     => 'Strategic Consultant',
            'description' => 'Ms. Sarika Narayan leverages over two decades of experience in business planning, product development, and marketing.',
            'mentorship'  => 'Business Strategy',
            'category'    => 'strategy',
            'image'       => '5sarika-YrDlypebENcVOJbw.jpg',
        ],
        [
            'id'          => 6,
            'name'        => 'Pratik Baheti',
            'designation' => 'Senior Engineer',
            'company'     => 'Capgemini',
            'description' => 'A seasoned engineer specializing in electronics with 9 years of expertise in high-tech product development.',
            'mentorship'  => 'Early Stage Ideation',
            'category'    => 'ideation',
            'image'       => '6pratik-AE0obZlGk5sXLgeQ.jpg',
        ],
        [
            'id'          => 7,
            'name'        => 'Ritwik Nikam',
            'designation' => 'Strategy Execution Manager',
            'company'     => 'Merck Life Sciences',
            'description' => 'Mr. Ritwik Nikam has 14 years of experience turning strategic visions into successful, sustainable business realities.',
            'mentorship'  => 'Business Strategy',
            'category'    => 'strategy',
            'image'       => '7ritwik-YBgr6n0WEVuloBLZ.jpg',
        ],
        [
            'id'          => 8,
            'name'        => 'Amit Rahalkar',
            'designation' => 'Senior Technology Program Manager',
            'company'     => 'Amazon',
            'description' => 'With 23 years of experience, he guides strategic engineering initiatives across global technology and e-commerce sectors.',
            'mentorship'  => 'Technology',
            'category'    => 'technology',
            'image'       => '8amit-dWxyDW7z60hMJ5Pr.jpg',
        ],
        [
            'id'          => 9,
            'name'        => 'Agha Ahmad',
            'designation' => 'Founder & President',
            'company'     => 'Afifa Foundation',
            'description' => 'A seasoned social entrepreneur dedicated to guiding impactful initiatives, early-stage scaling, and positive societal change.',
            'mentorship'  => 'Early Stage Ideation',
            'category'    => 'ideation',
            'image'       => '10agha-mk3zWpPrK4CkZwvw.jpg',
        ],
        [
            'id'          => 10,
            'name'        => 'Shabbir Sheikh',
            'designation' => 'Program Manager (e-Mobility)',
            'company'     => 'Schaeffler India Limited',
            'description' => 'Channels 16 years of expertise in fuel cell and thermal management technologies, advancing future automotive innovation.',
            'mentorship'  => 'Technology',
            'category'    => 'technology',
            'image'       => '12shabbir-dWxyDW7Ry2f6napX.jpg',
        ],
        [
            'id'          => 11,
            'name'        => 'Kartik Iyer',
            'designation' => 'Head of Operations',
            'company'     => 'Practo Technologies',
            'description' => 'Brings two decades of extensive leadership experience driving operational excellence and enhancing digital user experiences.',
            'mentorship'  => 'Operations',
            'category'    => 'operations',
            'image'       => '13kartik-AE0obZlLweSaEwBM.jpg',
        ],
        [
            'id'          => 12,
            'name'        => 'Akash Naoghare',
            'designation' => 'Founder',
            'company'     => 'Beejotsav & Akdee Clothing',
            'description' => 'Decade-long background spearheading ventures at the intersection of Agriculture, Food Systems, Sustainability, and Fashion.',
            'mentorship'  => 'Early Stage Ideation',
            'category'    => 'ideation',
            'image'       => '9adash-m2Wp3z7zbgSjRb4o.jpg',
        ],
        [
            'id'          => 13,
            'name'        => 'Nishchal Diwate',
            'designation' => 'Software Manager',
            'company'     => 'Bosch (Germany)',
            'description' => 'Accomplished Software Manager with 13 years of expertise driving complex software development at automotive technology frontlines.',
            'mentorship'  => 'Technology',
            'category'    => 'technology',
            'image'       => '15nishchal-AoPvXp9apOH3ZOZ8.jpg',
        ],
        [
            'id'          => 14,
            'name'        => 'Rohit Himte',
            'designation' => 'Managing Director',
            'company'     => 'Nodhrita Events Pvt. Ltd.',
            'description' => 'Leverages eight years of expertise in branding, public relations, and digital marketing in the competitive events industry.',
            'mentorship'  => 'Business Strategy',
            'category'    => 'strategy',
            'image'       => '16rohit-YNqyGjRnRahRDjgR.jpg',
        ],
        [
            'id'          => 15,
            'name'        => 'Mahavir Sharma',
            'designation' => 'Chairman',
            'company'     => 'Rajasthan Angels (RAIN)',
            'description' => 'Brings 13 years of expertise guiding early-stage startups and angel syndicates, fostering high-growth innovation ecosystems.',
            'mentorship'  => 'Early Stage Ideation',
            'category'    => 'ideation',
            'image'       => '17mahavir-dJo6yaR78eIq1Mgv.jpg',
        ],
        [
            'id'          => 16,
            'name'        => 'Ritesh Toshniwal',
            'designation' => 'Managing Partner',
            'company'     => 'ThinKuvate Ventures Pvt. Ltd.',
            'description' => 'Specializes in startup investments, technology marketing, venture capital, and enterprise go-to-market strategies with 25 years of mastery.',
            'mentorship'  => 'Early Stage Ideation',
            'category'    => 'ideation',
            'image'       => '18riteshtoshniwal-mv0DGpgoBqC0aXrx.jpg',
        ],
        [
            'id'          => 17,
            'name'        => 'Anand Tajpuriya',
            'designation' => 'Director',
            'company'     => 'ART Capital',
            'description' => 'Specializing in startup scaling, enterprise sales, capital allocation, and business development with over 15 years of expertise.',
            'mentorship'  => 'Marketing & Branding',
            'category'    => 'marketing',
            'image'       => '19anand-YD06JMR03wCopaME.jpg',
        ],
        [
            'id'          => 18,
            'name'        => 'Pankaj Holey',
            'designation' => 'Manager, Central Mfg Engg',
            'company'     => 'Mahindra & Mahindra Ltd.',
            'description' => 'Proficient in lean manufacturing and operational excellence with 17 years of experience in large-scale operations management.',
            'mentorship'  => 'Operations',
            'category'    => 'operations',
            'image'       => '20pankajholey-mP4ngER5kLs3wZ5y.jpg',
        ],
        [
            'id'          => 19,
            'name'        => 'Rupali Mudaliar',
            'designation' => 'FinTech Consultant',
            'company'     => 'IFSCA (Govt. of India)',
            'description' => 'Consultant at IFSCA with 11+ years of experience across FinTech innovation, legal structures, company secretarial, and regulatory compliance.',
            'mentorship'  => 'Legal & Compliance',
            'category'    => 'legal',
            'image'       => '22rupali-d95KLwkWLxu5bX4p.jpg',
        ],
        [
            'id'          => 20,
            'name'        => 'Amit Dubey',
            'designation' => 'Head Business Dev & Innovation',
            'company'     => 'Linamar India Pvt. Ltd.',
            'description' => 'Over 25 years of industry leadership in mechanical engineering sales, B2B marketing, industrial branding, and innovation pipeline development.',
            'mentorship'  => 'Marketing & Branding',
            'category'    => 'marketing',
            'image'       => '23amitdubey-YD06JMRjobHRReqz.jpg',
        ],
        [
            'id'          => 21,
            'name'        => 'Dheeraj Kumar',
            'designation' => 'Deputy Director & Director',
            'company'     => 'TEXMiN (IIT / ISM)',
            'description' => 'Two decades of technological leadership specializing in advanced technology implementation, deep-tech research, and mining automation.',
            'mentorship'  => 'Technology',
            'category'    => 'technology',
            'image'       => '24dheeraj-mk3zWpbyDrfDRLBN.jpg',
        ],
        [
            'id'          => 22,
            'name'        => 'Zulfikar Anis',
            'designation' => 'Senior Cost Engineer',
            'company'     => 'Aramco',
            'description' => 'A decade of global experience in industrial project controls, business strategy formulation, and capital optimization.',
            'mentorship'  => 'Business Strategy',
            'category'    => 'strategy',
            'image'       => '25zulfikar-Aq2v9p4NVoC35kVP.jpg',
        ],
        [
            'id'          => 23,
            'name'        => 'Raghu Kodumuri',
            'designation' => 'Senior Services Architect',
            'company'     => 'Okta',
            'description' => '25 years in IT enterprise architecture, cloud identity security, automation, and executing resilient digital business strategies.',
            'mentorship'  => 'Business Strategy',
            'category'    => 'strategy',
            'image'       => '26raghu-AQEyr7lyE2TGoovV.jpg',
        ],
        [
            'id'          => 24,
            'name'        => 'Ashish Shrivastava',
            'designation' => 'Head (IT)',
            'company'     => 'Bajaj Electricals Limited',
            'description' => 'General Manager of IT with 26 years of digital leadership in FMEG, smart manufacturing, enterprise IT, logistics, and BFSI sectors.',
            'mentorship'  => 'Technology',
            'category'    => 'technology',
            'image'       => '27ashish-YNqyGjRProU6y8ZK.jpg',
        ],
        [
            'id'          => 25,
            'name'        => 'Abhay Dudhankar',
            'designation' => 'Deputy Manager (IT)',
            'company'     => 'Arabian Rock Engineering Co.',
            'description' => 'Specializes in high-precision engineering, explosives tech, underground excavation systems, and industrial IT management.',
            'mentorship'  => 'Technology',
            'category'    => 'technology',
            'image'       => '28abhaydudhankar-mp8vQpyW5PUXG3NB.jpg',
        ],
        [
            'id'          => 26,
            'name'        => 'Sangita Rajankar',
            'designation' => 'Associate Scientist',
            'company'     => 'MRSAC',
            'description' => 'Focusing on geospatial technology and satellite data analysis with 20+ years of pioneering scientific research and application development.',
            'mentorship'  => 'Technology',
            'category'    => 'technology',
            'image'       => '29sangita-mp8vQpy4MLsxjE9P.jpg',
        ],
        [
            'id'          => 27,
            'name'        => 'Arnab Biswas',
            'designation' => 'Business Development Manager',
            'company'     => 'Amazon',
            'description' => 'Leads enterprise growth in life sciences, cloud infrastructure, and generative AI with 25 years of strategic leadership.',
            'mentorship'  => 'Business Strategy',
            'category'    => 'strategy',
            'image'       => '30arnab-dOqyV5Rp8KHleaBD.jpg',
        ],
        [
            'id'          => 28,
            'name'        => 'Neha Vedantwar',
            'designation' => 'Chief Executive Officer',
            'company'     => 'WhiteChalk Pvt. Ltd.',
            'description' => 'CEO specializing in digital performance marketing, growth hacking, and high-impact brand acceleration with 17 years of mastery.',
            'mentorship'  => 'Marketing & Branding',
            'category'    => 'marketing',
            'image'       => '31neha-AzGeop2Px9SZV0J4.jpg',
        ],
        [
            'id'          => 29,
            'name'        => 'Shivshankar Balasubramanian',
            'designation' => 'Finance Transformation Manager',
            'company'     => 'Google',
            'description' => 'Finance Transformation Manager at Google with over a decade in Hi-Tech, FinTech innovation, and tech venture financing strategy.',
            'mentorship'  => 'Finance',
            'category'    => 'finance',
            'image'       => '32shivshankar-YD06JMRb2Gu4yPxR.jpg',
        ],
        [
            'id'          => 30,
            'name'        => 'Ayush Tyagi',
            'designation' => 'Startup Mentor & Investor',
            'company'     => 'iStart Rajasthan',
            'description' => 'Brings 9+ years of ecosystem leadership as a community builder, investment director, and startup fundraising specialist.',
            'mentorship'  => 'Capital Management',
            'category'    => 'finance',
            'image'       => '33ayush-AQEyr7lwKlhWBOl8.jpg',
        ],
        [
            'id'          => 31,
            'name'        => 'Ravi Kikan',
            'designation' => 'Global Chief Marketing Officer',
            'company'     => 'United WeCare',
            'description' => '24 years of international experience driving cross-industry growth, marketing excellence, mental health advocacy, and brand strategy.',
            'mentorship'  => 'Marketing & Branding',
            'category'    => 'marketing',
            'image'       => '34ravi-YbNvjpEzryu5av22.jpg',
        ],
        [
            'id'          => 32,
            'name'        => 'Abid Ali',
            'designation' => 'Founder',
            'company'     => 'ByteWorks',
            'description' => 'Visionary product leader with 24 years driving cutting-edge advancements in Artificial Intelligence, Machine Learning, and software engineering.',
            'mentorship'  => 'Product Development',
            'category'    => 'product-development',
            'image'       => '35abid-mv0DGpgpBqtLONJn.jpg',
        ],
        [
            'id'          => 33,
            'name'        => 'Rhythm Goyal',
            'designation' => 'Associate Director',
            'company'     => 'Monotype',
            'description' => 'Over 14 years architecting resilient platform engineering frameworks and leading high-performing technical engineering teams.',
            'mentorship'  => 'Technology',
            'category'    => 'technology',
            'image'       => '36rhythm-YrDlypKr9etQ6DRo.jpg',
        ],
        [
            'id'          => 34,
            'name'        => 'Sushant Bhargava',
            'designation' => 'Senior Executive Manager',
            'company'     => 'Godrej & Boyce Mfg. Co. Ltd.',
            'description' => '16 years of multifaceted experience across consumer product manufacturing, operations management, and strategic market expansion.',
            'mentorship'  => 'Business Strategy',
            'category'    => 'strategy',
            'image'       => '37sushant-YanyLp589Wt9QQpD.jpg',
        ],
        [
            'id'          => 35,
            'name'        => 'Dr. Kirti Nikam',
            'designation' => 'Academician & Researcher',
            'company'     => 'Manipal School of Architecture',
            'description' => 'Distinguished professor and researcher fostering design thinking, sustainable architecture, and early-stage innovative prototyping.',
            'mentorship'  => 'Early Stage Ideation',
            'category'    => 'ideation',
            'image'       => '38kirti-AGB6XeRRqwc1a7ob.jpg',
        ],
        [
            'id'          => 36,
            'name'        => 'Sourabh Tapas',
            'designation' => 'SoC Functional Verification Lead',
            'company'     => 'NXP Semiconductors',
            'description' => 'Specialized in advanced microchip validation, semiconductor architecture, and embedded electronics hardware research.',
            'mentorship'  => 'Technology',
            'category'    => 'technology',
            'image'       => '39sourabh-dWxyDWZR36Hn6PLN.jpg',
        ],
        [
            'id'          => 37,
            'name'        => 'Devansh Lakhani',
            'designation' => 'Director',
            'company'     => 'Lakhani Financial Services',
            'description' => 'Specializes in venture capital fundraising, financial structuring, and accelerating startup traction from seed to Series A.',
            'mentorship'  => 'Funding & Capital Management',
            'category'    => 'finance',
            'image'       => '40devansh-A3QweqRevvfl4OLZ.jpg',
        ],
        [
            'id'          => 38,
            'name'        => 'Piyush Jha',
            'designation' => 'Product Marketing Manager',
            'company'     => 'Google India',
            'description' => 'Product marketing leader at Google with deep domain knowledge in go-to-market strategies, user experience design, and digital brand scaling.',
            'mentorship'  => 'Marketing & Branding',
            'category'    => 'marketing',
            'image'       => '41piyush-Yyv3rp8zPqcNBQLL.jpg',
        ],
        [
            'id'          => 39,
            'name'        => 'Vinod Midha',
            'designation' => 'Partner',
            'company'     => 'Simple Sell Solutions LLP',
            'description' => '49 years of legendary industry expertise pioneering product and business development across Energy, Defence, and Renewables.',
            'mentorship'  => 'Early Stage Ideation',
            'category'    => 'ideation',
            'image'       => '42vinod-YNqyGjRwe3U8aPNe.jpg',
        ],
        [
            'id'          => 40,
            'name'        => 'Shamik Ukil',
            'designation' => 'Chartered Accountant',
            'company'     => 'Advisory Monks Consulting',
            'description' => 'Chartered Accountant with 8 years of specialized mastery in legal structuring, startup auditing, financial compliance, and taxation.',
            'mentorship'  => 'Legal & Compliance',
            'category'    => 'legal',
            'image'       => '43shamik-YZ9V3wRL9JUJjDXD.jpg',
        ],
        [
            'id'          => 41,
            'name'        => 'Akshay Umbarkar',
            'designation' => 'Managing Partner',
            'company'     => 'Winspro EXIM',
            'description' => 'Over 13 years of leadership in cross-border trade, export-import logistics, startup incubation, and international product commercialization.',
            'mentorship'  => 'Product Development',
            'category'    => 'product-development',
            'image'       => '44akshay-mxBZgpRQO6UD2qwB.jpg',
        ],
        [
            'id'          => 42,
            'name'        => 'Gaurav Tripathi',
            'designation' => 'Co-founder & Group CTO',
            'company'     => 'Innoplexus',
            'description' => '20 years of visionary technology leadership, inventing transformative AI pipelines and high-throughput data platforms in Life Sciences.',
            'mentorship'  => 'Technology',
            'category'    => 'technology',
            'image'       => '45gaurav-AR0yovrZwRFJKMPk.jpg',
        ],
        [
            'id'          => 43,
            'name'        => 'Dr. Rajesh Jaware',
            'designation' => 'Incharge Innovation Management',
            'company'     => 'Maharashtra State Skills University',
            'description' => 'Professor and Innovation Incharge with 30 years of experience advancing Industrial Engineering, operations research, and incubation.',
            'mentorship'  => 'Early Stage Ideation',
            'category'    => 'ideation',
            'image'       => '46rajesh-YD06JMW0ZVhBQOqX.jpg',
        ],
        [
            'id'          => 44,
            'name'        => 'Monish Salhotra',
            'designation' => 'Innovation Officer',
            'company'     => 'NOISE',
            'description' => 'Spearheads disruptive hardware and wearable product development in consumer electronics with 12 years of industry acclaim.',
            'mentorship'  => 'Product Development',
            'category'    => 'product-development',
            'image'       => '47monish-m5KwB61gevsEP9Vr.jpg',
        ],
        [
            'id'          => 45,
            'name'        => 'Pankaj Katiyar',
            'designation' => 'Senior Manager Hardware Systems',
            'company'     => 'Micron Technology',
            'description' => 'Expertise in hardware system engineering, semiconductor reliability, and cutting-edge hardware-level computing architectures.',
            'mentorship'  => 'Product Development',
            'category'    => 'product-development',
            'image'       => '11pankaj-A0xwM7550BTJxEr2.jpg',
        ],
        [
            'id'          => 46,
            'name'        => 'Anshul Rathi',
            'designation' => 'Founder & CEO',
            'company'     => 'CertifyOS',
            'description' => 'Founder and CEO of CertifyOS, driving dynamic cybersecurity innovation, health-tech credentialing, and venture-backed scale.',
            'mentorship'  => 'Early Stage Ideation',
            'category'    => 'ideation',
            'image'       => '14anshul-d95KLwJXWbC21gG2.jpg',
        ],
    ];
}
